### ISSUE TITLE
App does not end when pressing home button / does not pause when in background

### ISSUE THREAD

**Issue by thasti** [thasti/LittleComputerPeople#24]
Sound keeps playing, which is annoying. IF we want to continue the simulation, we should at least stop the sounds.

**Comment by oObqpdOo** [comment]
Tried to Override:

    @Override
    public void onPause(){
        super.onPause();
        timer.cancel();             //Timer sauber beenden
    }

    @Override
    public void onResume(){
        super.onResume();
        timer = new Timer();
        timer.schedule(new TimerTask(){
            @Override
            public void run(){
                GlobalInformation.getSubject().tick();
                grafik.postInvalidate();
                InternalClock.computeTime();
            }
        }, 0, tick);
    }

App is muted when paused but subject is running with double speed

Also tried to pause and resume the TimerTask without success.

**Comment by oObqpdOo** [comment]
Ok, i think i fixed it (pull request #37)
