### ISSUE TITLE
HouseView

### ISSUE THREAD

**Issue by Ash0n** [thasti/LittleComputerPeople#32]
-funktioniert nicht (Schwarzes Bild)

**Comment by thasti** [comment]
Only in pull request #31

**Comment by oObqpdOo** [comment]
Kann man diesen "Issue" jetzt schließen?

**Comment by thasti** [comment]
Fixed by @oObqpdOo

**Comment by Ash0n** [comment]
Wurde eigentlich von mir in #31 gefixt
