### ISSUE TITLE
When touching Subject when it is in front of an Object, both touch events trigger.

### ISSUE THREAD

**Issue by thasti** [thasti/LittleComputerPeople#41]
@Mebodiel @snapesnap which behaviour is desired? Should the Chat or the object-touch-action have priority? Or the one that is in front of the other (for cases where objects are in front of the subject).

**Comment by snapesnap** [comment]
I'm in the opinion that the subject should hatve the priority. Because, if the user wants to touch the object, he can do that later when the subject is gone.
It makes more sense to me.

**Comment by Mebodiel** [comment]
@thasti Die Objekte sollten mMn immer Priorität haben.

 

Gesendet: Mittwoch, 07. Januar 2015 um 19:24 Uhr
Von: "Stefan Biereigel" <notifications@github.com>
An: thasti/LittleComputerPeople <LittleComputerPeople@noreply.github.com>
Cc: Mebodiel <johannesbackhaus@gmx.de>
Betreff: [LittleComputerPeople] When touching Subject when it is in front of an Object, both touch events trigger. (#41)


@Mebodiel @snapesnap which behaviour is desired? Should the Chat or the object-touch-action have priority? Or the one that is in front of the other (for cases where objects are in front of the subject).

**Comment by snapesnap** [comment]
ba dam tss
Und nun?

**Comment by Mebodiel** [comment]
Ich meinte, das Objekt hat dann  Priorität, wenn es vor dem Subjekt ist. Den Fall gibt es aber glaube ich garnicht, also würde ich auch sagen, das Subjekt hat Priorität . Immer was im Vordergrund ist, sollte Priortät haben, was also wirklich "berührt" wird.

 

Aber in Wirklichkeit ist mir das egaaaaaaaaal.

 

 

 

Gesendet: Mittwoch, 07. Januar 2015 um 20:35 Uhr
Von: MiCies <notifications@github.com>
An: thasti/LittleComputerPeople <LittleComputerPeople@noreply.github.com>
Cc: Mebodiel <johannesbackhaus@gmx.de>
Betreff: Re: [LittleComputerPeople] When touching Subject when it is in front of an Object, both touch events trigger. (#41)


ba dam tss
Und nun?

**Comment by snapesnap** [comment]
na schön, dann machen wir es eben, welches Objekt weiter "vorne" ist. Da das wahrscheinlich sowieso immer das Subjekt sein wird (nach deiner Aussage, Johannes), passt doch alles :+1:

**Comment by oObqpdOo** [comment]
fixed - Priorität hat der Button in der Ecke, dann das Subjekt und dann die Objekte
