### ISSUE TITLE
NeedsList

### ISSUE THREAD

**Issue by oObqpdOo** [thasti/LittleComputerPeople#43]
Needs List is empty - XML Parser needs to be revied (@fish08052013)

Error in line "needs_list.get(maxMotivationIndex).setCurrentValue(0);" (Intelligence)
"java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0"

**Comment by fish08052013** [comment]
Sorry Jungs, ein kleiner Schreibfehler->große Wirkung. Eindeutig mein 
Fehler, hätte die zurückzugebende Liste prüfen sollen und nicht nur ob 
das auslesen korrekt ist.

**Comment by oObqpdOo** [comment]
Fixed
